version: "3.4"

services:
  whisper-asr-webservice-gpu:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - ASR_ENGINE = openai_whisper #faster_whisper
      - ASR_MODEL = large-v3-turbo
      #- ASR_QUANTIZATION = float16
    ports:
      - "9000:9000"
    volumes:
      - cache-whisper:/root/.cache

volumes:
  cache-whisper:
