server:
  port: 8082

spring:
  application:
    name: llm-speaking
  docker:
    compose:
      readiness:
        timeout: 10m
      wait:
        log-patterns:
          zonos: "Uvicorn running on"
      lifecycle-management: start_only